name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.platform }}
    name: build on all platforms
    strategy:
      matrix:
        go-version: ["1.18", "1.20", "1.21"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version}}

    - name: Build
      env:
        GOPROXY: direct
        GO111MODULE: on
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
