name: lint
on:
  push:
    branches:
      - main 
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    
    name: uses golangci-golint on lsvpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1'
      - run: go version
      
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1
      - name: run golangci-lint
        run: GOGC=5 golangci-lint run -v ./... --out-format=github-actions
