name: lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    
    name: uses golangci-golint on lsvpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1'
      - run: go version
      
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: golangci-golint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1
          ./bin/golangci-lint run -v ./...
